In [50]:
import torch
import torch.nn.functional as F

In [23]:
# torch is row-major

# create tensor of shape filled with 0.
# 2d tensor of 3 rows and 3 columns 
torch.zeros((3,3)) # default dtype float32

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [18]:
# convert python list to tensor
xs = [0,1,2,3]
torch.tensor(xs)

tensor([0, 1, 2, 3])

In [19]:
# generate random numbers from standard normal distribution (mean 0 variance 1)
torch.randn((3,3))

tensor([[ 0.4742,  0.4657,  0.4172],
        [-1.4158,  0.3282, -0.9178],
        [ 1.7138, -0.7765,  0.2281]])

In [20]:
# generate numbers in a range
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [28]:
x = torch.tensor([[1,2,3], [4,5,6]]) # tensor of shape (2,3)

# keepdim is False by default so the dimension along which the sum is taken is not kept
row = x.sum(0) # collapse rows (column-wise sum)
col = x.sum(1) # collapse columns (row-wise sum)
print(row, row.shape) # shape changes to (3) i.e. column size
print(col, col.shape) # shape changes to (2) i.e. row size

# keepdim keep the dimensions
row = x.sum(0, keepdim=True) # collapse rows (column-wise sum)
col = x.sum(1, keepdim=True) # collapse columns (row-wise sum)
print(row, row.shape) # shape changes to (1,3) i.e. the collapsed row dimension is kept
print(col, col.shape) # shape changes to (2,1) i.e. the collapsed column dimension is kept

tensor([5, 7, 9]) torch.Size([3])
tensor([ 6, 15]) torch.Size([2])
tensor([[5, 7, 9]]) torch.Size([1, 3])
tensor([[ 6],
        [15]]) torch.Size([2, 1])


In [ ]:
# sample from multinomial distribution

p = torch.tensor([0.3, 0.7, 0.0])
# pick 10 samples such that the sample probability is p
# p = [0.3, 0.7, 0.0] means ~30% chance of 0, ~70% chance of 1, 0% chance of 2
# with replacement=True, each sample is independent
torch.multinomial(p, num_samples=10, replacement=True)

tensor([0, 0, 1, 1, 1, 1, 1, 0, 1, 0])

In [ ]:
# one hot encode
# used to deal with categorical data
# reformat categorical data into usable vector form to be fed into neural networks
# creates vector of size(total categories) where true category is 1 and every other category is 0
xs = torch.tensor([0,1,2])
F.one_hot(xs, num_classes=5).float()

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])

In [ ]:
# indexing

x = torch.tensor([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
print(x[0,0]) # 0th row, 0th column => 1
print(x[2,3]) # 2nd row, 3rd column => 14
print(x[torch.arange(3), 1]) # all rows, 1st column => [2,7,12], or..
print(x[:, 1]) # all rows, 1st column => [2,7,12]


tensor(1)
tensor(14)
tensor([ 2,  7, 12])
tensor([ 2,  7, 12])


In [ ]:
# convert dtypes
x = torch.tensor([1,2,3])
print(x.dtype) # int64
x = x.type(torch.int32)
print(x.dtype) # int32
x = x.type(torch.float32)
print(x.dtype) # float32

torch.int64
torch.int32
torch.float32
